CREATE TYPE rating AS ENUM (
  'G',
  'PG',
  'PG-13',
  'R',
  'NC-17'
);

CREATE TYPE role AS ENUM (
  'Actor',
  'VoiceActor'
);

CREATE TABLE persons (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE genres (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(30)
);

CREATE TABLE viewers (
  film_id integer,
  country_id integer,
  view_count integer NOT NULL,
  PRIMARY KEY (film_id, country_id)
);

CREATE TABLE countries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(30)
);

CREATE TABLE casts (
  film_id integer,
  person_id integer,
  role role NOT NULL,
  PRIMARY KEY (film_id, person_id)
);

CREATE TABLE box_office (
  film_id integer PRIMARY KEY,
  budget money,
  marketing money,
  money_made_in_usa money,
  money_made_in_world money
);

CREATE TABLE films (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slogan text,
  year integer,
  director_id integer,
  screenwriter_id integer,
  composer_id integer,
  artist_id integer,
  editor_id integer,
  cameraman_id integer,
  premiere_date Date,
  premiere_date_ru Date,
  dvd_release_date Date,
  age_restriction integer,
  mpaa_rating rating,
  length interval
);

CREATE INDEX person_name_index ON persons (name);

CREATE INDEX film_name_index ON films (name);

ALTER TABLE cast ADD FOREIGN KEY (film_id) REFERENCES films (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE cast ADD FOREIGN KEY (person_id) REFERENCES persons (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE box_office ADD FOREIGN KEY (film_id) REFERENCES films (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE viewers ADD FOREIGN KEY (film_id) REFERENCES films (id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE film_genre (
  film_id integer,
  genre_id integer,
  PRIMARY KEY (film_id, genre_id)
);

ALTER TABLE film_genre ADD FOREIGN KEY (film_id) REFERENCES films (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE film_genre ADD FOREIGN KEY (genre_id) REFERENCES genres (id) ON UPDATE CASCADE ON DELETE CASCADE;


ALTER TABLE films ADD FOREIGN KEY (director_id) REFERENCES persons (id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE films ADD FOREIGN KEY (screenwriter_id) REFERENCES persons (id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE films ADD FOREIGN KEY (composer_id) REFERENCES persons (id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE films ADD FOREIGN KEY (artist_id) REFERENCES persons (id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE films ADD FOREIGN KEY (editor_id) REFERENCES persons (id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE films ADD FOREIGN KEY (cameraman_id) REFERENCES persons (id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE viewers ADD FOREIGN KEY (country_id) REFERENCES countries (id) ON UPDATE CASCADE ON DELETE CASCADE;
